[tool.poetry]
name = "ageoverflow-tests"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
pendulum = "^3.2.0"
requests = "^2.32.5"
rfc3339-validator = "^0.1.4"
lorem = "^0.1.1"
pytest-github-report = "^0.0.1"
pytest-timeout = "^2.4.0"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
